local M = {}

function M.setup(colors, opts)
  local normal_bg = colors.bg
  if opts.transparent then
    normal_bg = nil
  end

  return {
    Normal = { fg = colors.fg, bg = normal_bg },
    NormalNC = { fg = colors.fg_dim, bg = normal_bg },
    NormalFloat = { fg = colors.fg, bg = colors.bg_float },
    FloatBorder = { fg = colors.fg, bg = colors.bg_float },
    FloatTitle = { fg = colors.accent, bg = colors.bg_float },
    ColorColumn = { bg = colors.bg_alt },
    Conceal = { fg = colors.accent },
    Cursor = { fg = colors.bg, bg = colors.fg },
    CursorColumn = { bg = colors.bg_alt },
    CursorLine = { bg = colors.bg_alt },
    CursorLineNr = { fg = colors.fg_dim, bg = colors.bg_alt },
    Directory = { fg = colors.accent },
    EndOfBuffer = { fg = colors.bg },
    ErrorMsg = { fg = colors.error, bold = true },
    FoldColumn = { fg = colors.hint, bg = normal_bg },
    Folded = { fg = colors.gutter, bg = colors.bg_alt },
    IncSearch = { fg = colors.bg_alt, bg = colors.value },
    LineNr = { fg = colors.gutter },
    LineNrAbove = { fg = colors.gutter },
    LineNrBelow = { fg = colors.gutter },
    MatchParen = { fg = colors.bg, bg = colors.gutter, bold = true },
    ModeMsg = { fg = colors.ok },
    MoreMsg = { fg = colors.ok },
    NonText = { fg = colors.gutter },
    Pmenu = { fg = colors.fg, bg = colors.bg_alt },
    PmenuSel = { fg = colors.bg_alt, bg = colors.fg },
    PmenuSbar = { bg = colors.bg_alt },
    PmenuThumb = { bg = colors.gutter },
    Question = { fg = colors.accent },
    QuickFixLine = { bg = colors.bg_alt },
    Search = { fg = colors.bg_alt, bg = colors.yellow },
    SignColumn = { fg = colors.gutter, bg = normal_bg },
    SpecialKey = { fg = colors.gutter },
    SpellBad = { undercurl = true, sp = colors.error },
    SpellCap = { undercurl = true, sp = colors.accent },
    SpellLocal = { undercurl = true, sp = colors.teal },
    SpellRare = { undercurl = true, sp = colors.teal },
    StatusLine = { fg = colors.fg, bg = colors.gutter },
    Statusline = { fg = colors.fg, bg = colors.gutter },
    StatusLineNC = { fg = colors.fg_dim, bg = colors.bg_alt },
    TabLine = { fg = colors.gutter, bg = colors.bg_alt },
    TabLineFill = { fg = colors.gutter, bg = colors.bg_alt },
    TabLineSel = { fg = colors.ok, bg = colors.bg_alt },
    Title = { fg = colors.accent },
    VertSplit = { fg = colors.fg, bg = normal_bg },
    Visual = { bg = colors.gutter },
    WarningMsg = { fg = colors.error },
    Whitespace = { fg = colors.gutter },
    WildMenu = { fg = colors.error, bg = colors.yellow },
    WinSeparator = { fg = colors.gutter },

    Comment = vim.tbl_extend("force", { fg = colors.comment }, opts.styles.comments),
    Constant = { fg = colors.value },
    String = vim.tbl_extend("force", { fg = colors.ok }, opts.styles.strings),
    Character = { fg = colors.error },
    Number = { fg = colors.value },
    Boolean = { fg = colors.value },
    Float = { fg = colors.value },
    Identifier = { fg = colors.error },
    Function = vim.tbl_extend("force", { fg = colors.accent }, opts.styles.functions),
    Statement = vim.tbl_extend("force", { fg = colors.error }, opts.styles.keywords),
    Conditional = { fg = colors.warn },
    Repeat = { fg = colors.yellow },
    Label = { fg = colors.yellow },
    Operator = { fg = colors.warn },
    Keyword = { fg = colors.warn },
    Exception = { fg = colors.error },
    PreProc = { fg = colors.yellow },
    Include = { fg = colors.accent },
    Define = { fg = colors.warn },
    Macro = { fg = colors.error },
    PreCondit = { fg = colors.yellow },
    Type = { fg = colors.yellow },
    StorageClass = { fg = colors.yellow },
    Structure = { fg = colors.warn },
    Typedef = { fg = colors.yellow },
    Special = { fg = colors.hint },
    SpecialChar = { fg = colors.teal },
    Tag = { fg = colors.yellow },
    Delimiter = { fg = colors.teal },
    SpecialComment = { link = "Comment" },
    Debug = { fg = colors.error },
    Underlined = { fg = colors.error, underline = true },
    Ignore = { fg = colors.gutter },
    Error = { fg = colors.error, bold = true },
    Todo = { fg = colors.yellow, bg = colors.bg_alt, bold = true },

    DiagnosticError = { fg = colors.error },
    DiagnosticWarn = { fg = colors.warn },
    DiagnosticInfo = { fg = colors.info },
    DiagnosticHint = { fg = colors.hint },
    DiagnosticOk = { fg = colors.ok },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.hint },
    DiagnosticUnderlineOk = { undercurl = true, sp = colors.ok },
    DiagnosticVirtualTextError = { fg = colors.error, bg = colors.bg_alt },
    DiagnosticVirtualTextWarn = { fg = colors.warn, bg = colors.bg_alt },
    DiagnosticVirtualTextInfo = { fg = colors.info, bg = colors.bg_alt },
    DiagnosticVirtualTextHint = { fg = colors.hint, bg = colors.bg_alt },
    DiagnosticVirtualTextOk = { fg = colors.ok, bg = colors.bg_alt },
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },
    DiagnosticSignError = { link = "DiagnosticError" },
    DiagnosticSignWarn = { link = "DiagnosticWarn" },
    DiagnosticSignInfo = { link = "DiagnosticInfo" },
    DiagnosticSignHint = { link = "DiagnosticHint" },
    DiagnosticSignOk = { link = "DiagnosticOk" },

    DiffAdd = { fg = colors.ok, bg = colors.bg_alt },
    DiffChange = { fg = colors.yellow, bg = colors.bg_alt },
    DiffDelete = { fg = colors.error, bg = colors.bg_alt },
    DiffText = { fg = colors.info, bg = colors.gutter },
    Added = { fg = colors.ok },
    Changed = { fg = colors.yellow },
    Removed = { fg = colors.error },

    LspReferenceText = { underline = true, sp = colors.fg_dim },
    LspReferenceRead = { underline = true, sp = colors.fg_dim },
    LspReferenceWrite = { underline = true, sp = colors.fg_dim },
    LspInlayHint = { fg = colors.gutter, italic = true },
    LspCodeLens = { fg = colors.comment },
    LspCodeLensSeparator = { fg = colors.gutter },
    LspSignatureActiveParameter = { fg = colors.yellow, bold = true },
  }
end

return M
