local M = {}

function M.setup(colors, opts)
  return {
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.error"] = { link = "DiagnosticError" },
    ["@comment.warning"] = { link = "DiagnosticWarn" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "DiagnosticInfo" },

    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Constant" },
    ["@constant.macro"] = { link = "Macro" },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { link = "String" },
    ["@string.regexp"] = { fg = colors.hint },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "Special" },
    ["@string.special.symbol"] = { link = "String" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },

    ["@function"] = { link = "Function" },
    ["@function.call"] = { link = "Function" },
    ["@function.builtin"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@constructor"] = { fg = colors.accent },
    ["@operator"] = { link = "Operator" },

    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.coroutine"] = { link = "Keyword" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "Operator" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Statement" },
    ["@keyword.storage"] = { link = "StorageClass" },

    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Special" },

    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = colors.yellow, italic = true },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Keyword" },
    ["@variable"] = vim.tbl_extend("force", { fg = colors.error }, opts.styles.variables),
    ["@variable.builtin"] = { fg = colors.error, italic = true },
    ["@variable.member"] = { fg = colors.fg },
    ["@variable.parameter"] = { fg = colors.fg },
    ["@property"] = { fg = colors.fg },
    ["@module"] = { fg = colors.error },
    ["@module.builtin"] = { fg = colors.error, italic = true },
    ["@label"] = { link = "Label" },

    ["@tag"] = { fg = colors.error },
    ["@tag.attribute"] = { fg = colors.yellow },
    ["@tag.delimiter"] = { fg = colors.teal },

    ["@namespace"] = { link = "@module" },
    ["@field"] = { link = "@variable.member" },
    ["@parameter"] = { link = "@variable.parameter" },
    ["@method"] = { link = "@function.method" },
    ["@method.call"] = { link = "@function.method.call" },
    ["@text"] = { fg = colors.fg },
    ["@text.strong"] = { bold = true },
    ["@text.emphasis"] = { italic = true },
    ["@text.underline"] = { underline = true },
    ["@text.uri"] = { link = "Underlined" },
  }
end

return M
